- name: Recoge facts
  hosts: localhost
  tags:
    - always
  tasks:
    - name: Despliegue instancia.
      os_project_facts:
        cloud: awesomecloud
        name: demoproject
        domain: admindomain
        filters:
          enabled: False
