- name: Recoge facts
  hosts: localhost
  tags:
    - always
  tasks:
    - name: Despliegue instancia.
      os_project_facts:
        auth:
        auth_url: "{{ auth_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        project_name: "{{ project_name }}"
        domain_name: "{{ domain_name }}"
        filters:
          enabled: False
